[package]
name = "corvo-weather"
version = "0.5.1"
edition = "2021"
publish = false

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
corvo-core = { workspace = true }
corvo-ext = { workspace = true }
serde_json = "1"
smol = { workspace = true }
ureq = { workspace = true }
