//! Generates linker anchors for every command crate under `commands/`.
//!
//! Command crates reach the binary only through `inventory` section
//! statics, and the linker never pulls objects from unreferenced rlibs.
//! Each command crate therefore needs one code-level reference. This
//! script scans `commands/*/Cargo.toml` and writes one `use <crate>
//! as _;` anchor per crate, so adding a command stays: one crate, one
//! workspace member line, one dependency line. `main.rs` includes the
//! generated file and is never edited for a new command.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let commands_dir = manifest_dir.join("commands");
    println!("cargo:rerun-if-changed={}", commands_dir.display());

    let mut anchors = String::from(
        "// Generated by corvo's build.rs from the crates under commands/.\n\
         // Keeps every command crate linked so `inventory` registrations\n\
         // survive dead stripping.\n",
    );

    let entries = match fs::read_dir(&commands_dir) {
        Ok(entries) => entries,
        Err(err) => {
            println!("cargo:warning=corvo build.rs cannot read {}: {err}", commands_dir.display());
            return;
        }
    };

    let mut names: Vec<String> = Vec::new();
    for entry in entries.flatten() {
        let manifest = entry.path().join("Cargo.toml");
        let Ok(source) = fs::read_to_string(&manifest) else { continue };
        let Some(name) = package_name(&source) else { continue };
        let ident = name.replace('-', "_");
        if ident.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
            && ident.chars().next().is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        {
            names.push(ident);
        }
    }
    names.sort();
    names.dedup();

    for ident in names {
        anchors.push_str("#[allow(unused_imports)]\n");
        anchors.push_str(&format!("use {ident} as _;\n"));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("linked_commands.rs"), anchors)
        .expect("corvo build.rs cannot write linked_commands.rs");
}

/// Reads `name = "..."` from a crate manifest. Cargo always writes the
/// package name as the first table value, before any `[table]` header.
fn package_name(source: &str) -> Option<String> {
    source.lines().map(str::trim).find_map(|line| {
        let value = line.strip_prefix("name")?.trim().strip_prefix('=')?.trim();
        let name = value.strip_prefix('"')?.strip_suffix('"')?;
        (!name.is_empty()).then(|| name.to_string())
    })
}
