//! Emoji search over a static corpus with `frizbee` matching.
//!
//! Selecting a result copies the glyph to the clipboard; the user
//! pastes it into the previously focused app.

use corvo_core::{
    phosphor_svgs, Action, ActionGroup, Command, CommandAction, CommandError, ExecutionContext,
    search_match_score, Icon, SearchContext, SearchResult,
};

/// The glyph plus the keyword strings it answers to. The first keyword
/// is the display name.
const EMOJI: &[(&str, &str)] = &[
    ("😀", "grinning face smile happy"),
    ("😃", "smiley face happy joy"),
    ("😄", "smile face happy laugh"),
    ("😁", "grin face beam happy"),
    ("😆", "laughing squint smile"),
    ("😅", "sweat smile relief nervous"),
    ("🤣", "rolling on the floor laugh rofl"),
    ("😂", "joy face laugh tears cry funny"),
    ("🙂", "slightly smiling face"),
    ("🙃", "upside down face silly"),
    ("🫠", "melting face hot"),
    ("😉", "winking face wink"),
    ("😊", "blush smile warm shy"),
    ("😇", "halo angel innocent"),
    ("🥰", "smiling hearts love adore"),
    ("😍", "heart eyes love crush"),
    ("🤩", "star struck wow excited"),
    ("😘", "kiss love"),
    ("😜", "winking tongue silly"),
    ("🤪", "zany face crazy silly"),
    ("😝", "squinting tongue taste"),
    ("😛", "tongue out playful"),
    ("🤑", "money mouth rich dollar"),
    ("🤗", "hug open hands"),
    ("🤭", "giggle hand mouth"),
    ("🫣", "peek face shy hiding"),
    ("🤫", "shush quiet secret"),
    ("🤔", "thinking face hmm wonder"),
    ("🫡", "salute respect"),
    ("🤐", "zipper mouth silent"),
    ("🤨", "raised eyebrow suspicious"),
    ("😐", "neutral face meh"),
    ("😑", "expressionless blank"),
    ("😶", "no mouth speechless"),
    ("🫥", "dotted outline invisible"),
    ("😏", "smirk smug"),
    ("😒", "unamused annoyed"),
    ("🙄", "eye roll annoyed"),
    ("😬", "grimace awkward"),
    ("😮‍💨", "exhale sigh relief"),
    ("🤥", "lying pinocchio"),
    ("🫨", "shaking face tremble"),
    ("😌", "relieved calm"),
    ("😔", "pensive sad"),
    ("😪", "sleepy tired"),
    ("🤤", "drool hungry"),
    ("😴", "sleeping face zzz snore"),
    ("😷", "mask sick covid"),
    ("🤒", "sick thermometer fever ill"),
    ("🤕", "bandage hurt injured"),
    ("🤢", "nausea sick vomit"),
    ("🤮", "vomit puke sick"),
    ("🤧", "sneeze sick"),
    ("🥵", "hot fever heat"),
    ("🥶", "cold freeze ice"),
    ("😶‍🌫️", "face in clouds fog confused"),
    ("🥴", "woozy drunk dizzy"),
    ("😵", "dizzy dead knocked"),
    ("🤯", "mind blown explode wow"),
    ("🤠", "cowboy hat yeehaw"),
    ("🥳", "party celebrate birthday tada"),
    ("🥸", "disguise glasses incognito"),
    ("😎", "cool sunglasses swag"),
    ("🤓", "nerd glasses smart"),
    ("🧐", "monocle fancy inspect"),
    ("😕", "confused unsure"),
    ("🫤", "diagonal mouth unsure"),
    ("😟", "worried concerned"),
    ("🙁", "slightly frown sad"),
    ("☹️", "frown sad"),
    ("😮", "open mouth wow surprise"),
    ("😯", "hushed surprised"),
    ("😲", "astonished shock wow"),
    ("🥹", "holding back tears touched"),
    ("😢", "cry tear sad"),
    ("😭", "sob cry tears loud"),
    ("😤", "triumph steam frustrated"),
    ("😠", "angry mad"),
    ("😡", "rage red angry furious"),
    ("🤬", "swear curse angry"),
    ("😈", "devil evil horns"),
    ("👿", "angry devil imp"),
    ("💀", "skull dead death"),
    ("☠️", "skull crossbones poison dead pirate"),
    ("💩", "poop shit"),
    ("🤡", "clown funny"),
    ("👹", "ogre monster japanese"),
    ("👺", "goblin tengu monster"),
    ("👻", "ghost spooky halloween boo"),
    ("👽", "alien ufo extraterrestrial"),
    ("👾", "space invader alien game pixel"),
    ("🤖", "robot bot ai"),
    // hands
    ("👋", "waving hand hello hi bye wave"),
    ("🤚", "raised back hand high five"),
    ("🖐️", "open hand fingers"),
    ("✋", "raised hand stop high five"),
    ("🫲", "leftwards hand"),
    ("🫱", "rightwards hand"),
    ("🫳", "palm down hand"),
    ("🫴", "palm up hand"),
    ("🫷", "pushing left"),
    ("🫸", "pushing right"),
    ("👌", "ok hand perfect zero"),
    ("🤌", "pinched fingers italian chef"),
    ("✌️", "victory peace two"),
    ("🤞", "crossed fingers luck hope"),
    ("🫰", "hand heart fingers love korean"),
    ("🤟", "love you rock sign"),
    ("🤘", "metal rock horns"),
    ("🤙", "call me shaka hang loose"),
    ("👈", "point left back"),
    ("👉", "point right forward"),
    ("👆", "point up one"),
    ("🖕", "middle finger rude"),
    ("👇", "point down"),
    ("☝️", "point up index"),
    ("🫵", "point at you"),
    ("👍", "thumbs up yes ok approve like"),
    ("👎", "thumbs down no disapprove dislike"),
    ("✊", "fist punch power"),
    ("👊", "fist bump oncoming"),
    ("👏", "clapping hands applause bravo"),
    ("🙌", "raised hands hooray praise"),
    ("👐", "open hands hug"),
    ("🤲", "palms up together pray"),
    ("🤝", "handshake deal agree shake"),
    ("🙏", "folded hands pray thanks please namaste"),
    ("✍️", "writing hand write"),
    ("💅", "nail polish beauty"),
    ("🤳", "selfie camera photo"),
    ("💪", "flexed biceps muscle strong gym"),
    ("🦾", "mechanical arm prosthetic"),
    ("🦿", "mechanical leg prosthetic"),
    ("🦵", "leg kick"),
    ("🦶", "foot kick step"),
    ("👂", "ear listen hear"),
    ("🦻", "ear hearing aid deaf"),
    ("👃", "nose smell sniff"),
    ("👀", "eyes look watch see"),
    ("👁️", "eye see watch"),
    ("👅", "tongue taste lick"),
    ("👄", "lips mouth kiss"),
    ("🫦", "biting lip nervous"),
    ("💋", "kiss mark lips lipstick"),
    ("🩸", "blood drop donate"),
    // hearts and symbols
    ("❤️", "red heart love"),
    ("🧡", "orange heart love"),
    ("💛", "yellow heart love"),
    ("💚", "green heart love"),
    ("💙", "blue heart love"),
    ("🩵", "light blue heart"),
    ("💜", "purple heart love"),
    ("🖤", "black heart dark"),
    ("🩶", "grey heart"),
    ("🤍", "white heart"),
    ("🤎", "brown heart"),
    ("🩷", "pink heart"),
    ("💔", "broken heart heartbreak sad"),
    ("❤️‍🔥", "heart on fire love passionate"),
    ("❤️‍🩹", "mending heart healing recover"),
    ("💕", "two hearts love"),
    ("💞", "revolving hearts love"),
    ("💓", "beating heart love pulse"),
    ("💗", "growing heart love"),
    ("💖", "sparkling heart love"),
    ("💘", "arrow heart cupid love"),
    ("💝", "gift heart ribbon love"),
    ("💟", "heart decoration"),
    ("💌", "love letter envelope romance"),
    ("💤", "sleep snore zzz"),
    ("💢", "anger rage mad"),
    ("💥", "collision boom explosion bang"),
    ("💫", "dizzy star swirl"),
    ("💦", "sweat water drops"),
    ("💨", "dash wind fast smoke"),
    ("🕳️", "hole"),
    ("💣", "bomb"),
    ("🧨", "firecracker dynamite"),
    ("✨", "sparkles shiny magic new clean"),
    ("⭐", "star favorite rate"),
    ("🌟", "glowing star sparkle"),
    ("💫", "dizzy star"),
    ("🌠", "shooting star wish"),
    ("🌌", "milky way galaxy space"),
    ("☄️", "comet meteor"),
    ("🔥", "fire hot lit flame"),
    ("🌪️", "tornado cyclone storm"),
    ("🌈", "rainbow pride"),
    ("☀️", "sun sunny weather"),
    ("🌤️", "sun behind small cloud"),
    ("⛅", "sun behind cloud"),
    ("🌦️", "sun behind rain cloud"),
    ("🌧️", "rain cloud weather"),
    ("⛈️", "thunderstorm lightning"),
    ("🌩️", "lightning cloud"),
    ("❄️", "snowflake snow cold winter"),
    ("☃️", "snowman winter"),
    ("⛄", "snowman without snow"),
    ("🌊", "wave ocean surf"),
    ("💧", "droplet water tear"),
    ("🌫️", "fog mist"),
    ("🌪️", "tornado"),
    ("🌍", "globe europe africa earth world"),
    ("🌎", "globe americas earth world"),
    ("🌏", "globe asia earth world"),
    ("🌐", "globe meridians internet web"),
    ("🌑", "new moon dark"),
    ("🌒", "waxing crescent moon"),
    ("🌓", "first quarter moon"),
    ("🌔", "waxing gibbous moon"),
    ("🌕", "full moon"),
    ("🌖", "waning gibbous moon"),
    ("🌗", "last quarter moon"),
    ("🌘", "waning crescent moon"),
    ("🌙", "crescent moon night"),
    ("🌚", "new moon face"),
    ("🌝", "full moon face"),
    ("🌞", "sun face happy"),
    ("⭐", "star"),
    ("💫", "dizzy"),
    // animals
    ("🐶", "dog puppy pet"),
    ("🐱", "cat kitten pet"),
    ("🐭", "mouse rat"),
    ("🐹", "hamster pet"),
    ("🐰", "rabbit bunny easter"),
    ("🦊", "fox"),
    ("🐻", "bear teddy"),
    ("🐼", "panda"),
    ("🐨", "koala"),
    ("🐯", "tiger"),
    ("🦁", "lion"),
    ("🐮", "cow"),
    ("🐷", "pig"),
    ("🐸", "frog"),
    ("🐵", "monkey"),
    ("🙈", "see no evil monkey"),
    ("🙉", "hear no evil monkey"),
    ("🙊", "speak no evil monkey"),
    ("🐒", "monkey"),
    ("🐔", "chicken"),
    ("🐧", "penguin"),
    ("🐦", "bird"),
    ("🐤", "baby chick"),
    ("🦆", "duck"),
    ("🦅", "eagle"),
    ("🦉", "owl wise"),
    ("🦇", "bat vampire"),
    ("🐺", "wolf"),
    ("🐗", "boar pig"),
    ("🐴", "horse"),
    ("🦄", "unicorn magic"),
    ("🐝", "bee honey buzz"),
    ("🐛", "bug worm"),
    ("🦋", "butterfly"),
    ("🐌", "snail slow"),
    ("🐞", "ladybug beetle"),
    ("🐢", "turtle slow"),
    ("🐍", "snake"),
    ("🦎", "lizard gecko"),
    ("🐙", "octopus kraken"),
    ("🦑", "squid"),
    ("🦐", "shrimp"),
    ("🦞", "lobster"),
    ("🦀", "crab"),
    ("🐡", "blowfish puffer"),
    ("🐠", "tropical fish"),
    ("🐟", "fish"),
    ("🐬", "dolphin"),
    ("🐳", "spouting whale"),
    ("🐋", "whale"),
    ("🦈", "shark jaws"),
    ("🐊", "crocodile alligator"),
    ("🐅", "tiger"),
    ("🐆", "leopard"),
    ("🦓", "zebra"),
    ("🦍", "gorilla"),
    ("🦧", "orangutan"),
    ("🐘", "elephant"),
    ("🦛", "hippo"),
    ("🦏", "rhino"),
    ("🐪", "camel"),
    ("🦒", "giraffe"),
    ("🦘", "kangaroo"),
    ("🐃", "water buffalo"),
    ("🐂", "ox bull"),
    ("🐄", "cow milk"),
    // food
    ("🍏", "green apple fruit"),
    ("🍎", "red apple fruit mac"),
    ("🍐", "pear fruit"),
    ("🍊", "tangerine orange fruit"),
    ("🍋", "lemon citrus"),
    ("🍌", "banana fruit"),
    ("🍉", "watermelon fruit"),
    ("🍇", "grapes fruit wine"),
    ("🍓", "strawberry berry fruit"),
    ("🫐", "blueberries berry"),
    ("🍈", "melon cantaloupe"),
    ("🍒", "cherries fruit"),
    ("🍑", "peach fruit butt"),
    ("🥭", "mango fruit"),
    ("🍍", "pineapple fruit"),
    ("🥥", "coconut"),
    ("🥝", "kiwi fruit"),
    ("🍅", "tomato"),
    ("🍆", "eggplant aubergine"),
    ("🥑", "avocado guac"),
    ("🥦", "broccoli vegetable"),
    ("🥬", "leafy greens salad"),
    ("🥒", "cucumber pickle"),
    ("🌶️", "hot pepper spicy chili"),
    ("🫑", "bell pepper"),
    ("🌽", "corn maize"),
    ("🥕", "carrot"),
    ("🫒", "olive"),
    ("🧄", "garlic"),
    ("🧅", "onion"),
    ("🍄", "mushroom"),
    ("🥜", "peanuts nuts"),
    ("🫘", "beans"),
    ("🌰", "chestnut"),
    ("🍞", "bread loaf"),
    ("🥐", "croissant french breakfast"),
    ("🥖", "baguette bread french"),
    ("🫓", "flatbread"),
    ("🥨", "pretzel"),
    ("🧀", "cheese"),
    ("🥚", "egg"),
    ("🍳", "fried egg breakfast cooking"),
    ("🧈", "butter"),
    ("🥞", "pancakes breakfast"),
    ("🧇", "waffle breakfast"),
    ("🥓", "bacon"),
    ("🥩", "meat steak beef cut"),
    ("🍗", "poultry leg chicken drumstick"),
    ("🍖", "meat bone bbq"),
    ("🌭", "hot dog"),
    ("🍔", "hamburger burger fast food"),
    ("🍟", "french fries fast food"),
    ("🍕", "pizza slice food"),
    ("🫔", "tamale"),
    ("🌮", "taco mexican"),
    ("🌯", "burrito wrap mexican"),
    ("🫕", "fondue"),
    ("🥙", "stuffed flatbread kebab"),
    ("🧆", "falafel"),
    ("🥚", "egg"),
    ("🍲", "pot food stew soup"),
    ("🫖", "teapot tea"),
    ("☕", "coffee hot beverage tea morning"),
    ("🍵", "tea cup matcha"),
    ("🧃", "juice box"),
    ("🥤", "cup straw soda"),
    ("🧋", "bubble tea boba"),
    ("🍺", "beer mug drink cheers"),
    ("🍻", "beers clinking cheers toast"),
    ("🥂", "champagne toast celebrate"),
    ("🍷", "wine glass red drink"),
    ("🥃", "whisky tumbler drink"),
    ("🍸", "cocktail martini drink"),
    ("🍹", "tropical drink cocktail"),
    ("🍾", "bottle popping champagne celebrate"),
    ("🧊", "ice cube cold"),
    ("🥄", "spoon"),
    ("🍴", "fork knife dinner eat"),
    ("🍽️", "plate dinner"),
    ("🥣", "bowl cereal soup"),
    ("🥡", "takeout box chinese"),
    ("🍱", "bento box japanese lunch"),
    ("🍘", "rice cracker"),
    ("🍙", "rice ball onigiri japanese"),
    ("🍚", "cooked rice"),
    ("🍛", "curry rice"),
    ("🍜", "noodles ramen bowl"),
    ("🍝", "spaghetti pasta italian"),
    ("🍠", "sweet potato roasted"),
    ("🍢", "oden skewer"),
    ("🍣", "sushi japanese"),
    ("🍤", "fried shrimp tempura"),
    ("🍥", "fish cake narutomaki"),
    ("🥮", "mooncake"),
    ("🍡", "dango dessert japanese"),
    ("🥟", "dumpling gyoza"),
    ("🥠", "fortune cookie"),
    ("🥡", "takeout"),
    ("🦪", "oyster"),
    ("🍦", "ice cream soft serve dessert"),
    ("🍧", "shaved ice dessert"),
    ("🍨", "ice cream bowl dessert"),
    ("🍩", "donut doughnut sweet"),
    ("🍪", "cookie sweet"),
    ("🎂", "birthday cake party"),
    ("🍰", "cake slice dessert"),
    ("🧁", "cupcake dessert"),
    ("🥧", "pie dessert"),
    ("🍫", "chocolate bar sweet"),
    ("🍬", "candy sweet"),
    ("🍭", "lollipop candy sweet"),
    ("🍮", "custard flan dessert"),
    ("🍯", "honey pot"),
    // objects
    ("⌚", "watch apple time"),
    ("📱", "mobile phone iphone smartphone"),
    ("📲", "phone arrow call"),
    ("💻", "laptop computer macbook code work"),
    ("⌨️", "keyboard typing"),
    ("🖥️", "desktop computer imac monitor"),
    ("🖨️", "printer print"),
    ("🖱️", "mouse computer click"),
    ("🖲️", "trackball"),
    ("🕹️", "joystick game arcade"),
    ("🗜️", "clamp tool"),
    ("💽", "cd disk"),
    ("💾", "floppy disk save"),
    ("💿", "cd disc"),
    ("📀", "dvd disc"),
    ("📼", "vhs tape retro"),
    ("📷", "camera photo picture"),
    ("📸", "camera flash photo"),
    ("📹", "video camera record"),
    ("🎥", "movie camera film cinema"),
    ("📽️", "projector film cinema"),
    ("🎞️", "film frames cinema"),
    ("📞", "phone receiver call"),
    ("☎️", "telephone landline call"),
    ("📟", "pager beeper retro"),
    ("📠", "fax machine"),
    ("📺", "television tv"),
    ("📻", "radio"),
    ("🎙️", "studio microphone podcast"),
    ("🎚️", "slider audio mixer"),
    ("🎛️", "control knobs audio"),
    ("🧭", "compass navigation"),
    ("⏱️", "stopwatch timer"),
    ("⏲️", "timer clock"),
    ("⏰", "alarm clock wake time"),
    ("🕰️", "mantel clock time"),
    ("⌛", "hourglass done time"),
    ("⏳", "hourglass flowing wait time"),
    ("📡", "satellite dish signal"),
    ("🔋", "battery charge power"),
    ("🔌", "plug electric power"),
    ("💡", "light bulb idea"),
    ("🔦", "flashlight torch"),
    ("🕯️", "candle light"),
    ("🪔", "diya lamp"),
    ("🧯", "fire extinguisher"),
    ("🛢️", "oil drum"),
    ("💸", "money wings spend"),
    ("💵", "dollar bill money cash"),
    ("💴", "yen bill money"),
    ("💶", "euro bill money"),
    ("💷", "pound bill money"),
    ("🪙", "coin money"),
    ("💰", "money bag rich dollar"),
    ("💳", "credit card pay"),
    ("💎", "gem diamond jewel"),
    ("⚖️", "scales balance justice"),
    ("🪜", "ladder"),
    ("🧰", "toolbox tools"),
    ("🪛", "screwdriver tool"),
    ("🔧", "wrench tool fix"),
    ("🔨", "hammer tool build"),
    ("⚒️", "hammer pick tools"),
    ("🛠️", "hammer wrench tools build fix"),
    ("⛏️", "pick mining"),
    ("🪓", "axe chop"),
    ("🧨", "dynamite firecracker"),
    ("🔩", "nut bolt hardware"),
    ("⚙️", "gear settings config cog"),
    ("🪤", "mousetrap"),
    ("🧱", "bricks wall build"),
    ("⛓️", "chains link"),
    ("🧲", "magnet attract"),
    ("🔫", "water pistol gun"),
    ("💣", "bomb"),
    ("🧨", "firecracker"),
    ("🪃", "boomerang"),
    ("🏹", "bow arrow archery"),
    ("🛡️", "shield protect security"),
    ("🪚", "saw cut wood"),
    ("🔧", "wrench"),
    ("🪞", "mirror"),
    ("🪟", "window"),
    ("🛏️", "bed sleep"),
    ("🛋️", "couch sofa"),
    ("🪑", "chair seat"),
    ("🚪", "door"),
    ("🪞", "mirror"),
    ("🧸", "teddy bear toy"),
    ("🪆", "nesting dolls russian"),
    ("🖼️", "framed picture art"),
    ("🧵", "thread sewing"),
    ("🪡", "needle sewing"),
    ("🧶", "yarn knit"),
    ("👓", "glasses spectacles"),
    ("🕶️", "sunglasses cool"),
    ("🥽", "goggles swim"),
    ("🥼", "lab coat science doctor"),
    ("🦺", "safety vest"),
    ("👔", "necktie shirt formal"),
    ("👗", "dress clothing"),
    ("👙", "bikini swim"),
    ("🩱", "one piece swimsuit"),
    ("🩲", "briefs underwear"),
    ("🩳", "shorts"),
    ("👖", "jeans pants"),
    ("👕", "tshirt shirt"),
    ("👚", "blouse shirt woman"),
    ("👛", "purse bag"),
    ("👜", "handbag bag"),
    ("👝", "clutch bag"),
    ("🛍️", "shopping bags buy"),
    ("🎒", "backpack school bag"),
    ("🧳", "luggage suitcase travel"),
    ("👞", "shoe man"),
    ("👟", "sneaker running shoe"),
    ("🥾", "hiking boot"),
    ("🥿", "flat shoe ballet"),
    ("👠", "high heel shoe"),
    ("👡", "sandal"),
    ("🩴", "flip flop thong sandal"),
    ("👢", "boot"),
    ("👑", "crown king royal"),
    ("👒", "hat woman sun"),
    ("🎩", "top hat magic formal"),
    ("🎓", "graduation cap university degree"),
    ("🧢", "cap baseball hat"),
    ("🪖", "military helmet"),
    ("⛑️", "rescue helmet"),
    ("📿", "prayer beads"),
    ("💄", "lipstick makeup"),
    ("💍", "ring diamond wedding"),
    ("💎", "gem"),
    // symbols
    ("❤️", "heart"),
    ("💯", "hundred points perfect score"),
    ("🔢", "numbers input 123"),
    ("🔣", "symbols input"),
    ("🔠", "uppercase abc"),
    ("🔡", "lowercase abc"),
    ("🔤", "letters abc input"),
    ("ℹ️", "information info"),
    ("🆔", "id badge identity"),
    ("Ⓜ️", "metro m subway"),
    ("🆕", "new button fresh"),
    ("🆖", "ng no good"),
    ("🆗", "ok button yes"),
    ("🆙", "up button"),
    ("🆒", "cool button"),
    ("🆓", "free button"),
    ("🆚", "versus vs"),
    ("🈁", "japanese here katakana"),
    ("🈶", "japanese not free charge"),
    ("🈯", "japanese reserved"),
    ("🉐", "japanese bargain"),
    ("🈹", "japanese discount"),
    ("🈚", "japanese free of charge"),
    ("🈲", "japanese prohibited"),
    ("🉑", "japanese acceptable"),
    ("🈸", "japanese application"),
    ("🈴", "japanese passing grade"),
    ("🈳", "japanese vacancy"),
    ("㊗️", "japanese congratulations"),
    ("㊙️", "japanese secret"),
    ("🈺", "japanese open business"),
    ("🈵", "japanese no vacancy full"),
    ("🔴", "red circle"),
    ("🟠", "orange circle"),
    ("🟡", "yellow circle"),
    ("🟢", "green circle"),
    ("🔵", "blue circle"),
    ("🟣", "purple circle"),
    ("⚫", "black circle"),
    ("⚪", "white circle"),
    ("🟤", "brown circle"),
    ("🔺", "red triangle up"),
    ("🔻", "red triangle down"),
    ("🔸", "orange small diamond"),
    ("🔹", "blue small diamond"),
    ("🔶", "orange large diamond"),
    ("🔷", "blue large diamond"),
    ("🔳", "white square button"),
    ("🔲", "black square button"),
    ("▪️", "black small square"),
    ("▫️", "white small square"),
    ("◾", "black medium small square"),
    ("◽", "white medium small square"),
    ("◼️", "black medium square"),
    ("◻️", "white medium square"),
    ("🟥", "red square"),
    ("🟧", "orange square"),
    ("🟨", "yellow square"),
    ("🟩", "green square"),
    ("🟦", "blue square"),
    ("🟪", "purple square"),
    ("⬛", "black large square"),
    ("⬜", "white large square"),
    ("✅", "check mark button yes done complete green"),
    ("☑️", "checkbox check ballot"),
    ("✔️", "check mark yes correct"),
    ("❌", "cross mark no wrong delete red"),
    ("❎", "cross mark button no"),
    ("➕", "plus add new math"),
    ("➖", "minus subtract remove math"),
    ("➗", "divide math"),
    ("✖️", "multiply math x"),
    ("🟰", "heavy equals math"),
    ("➰", "curly loop"),
    ("➿", "double curly loop"),
    ("〽️", "part alternation mark"),
    ("✳️", "eight spoked asterisk"),
    ("✴️", "eight pointed star"),
    ("❇️", "sparkle star"),
    ("©️", "copyright c"),
    ("®️", "registered r"),
    ("™️", "trademark tm"),
    ("🔚", "end arrow"),
    ("🔙", "back arrow"),
    ("🔛", "on arrow"),
    ("🔝", "top arrow"),
    ("🔜", "soon arrow"),
    ("✔️", "check"),
    ("☑️", "checkbox"),
    // arrows and UI
    ("⬆️", "up arrow"),
    ("↗️", "up right arrow"),
    ("➡️", "right arrow next forward"),
    ("↘️", "down right arrow"),
    ("⬇️", "down arrow"),
    ("↙️", "down left arrow"),
    ("⬅️", "left arrow back previous"),
    ("↖️", "up left arrow"),
    ("↕️", "up down arrow"),
    ("↔️", "left right arrow"),
    ("↩️", "curved left arrow return back"),
    ("↪️", "curved right arrow"),
    ("⤴️", "up right arrow curve"),
    ("⤵️", "down right arrow curve"),
    ("🔃", "clockwise arrows reload refresh"),
    ("🔄", "counterclockwise refresh reload sync"),
    ("🔙", "back"),
    ("🔚", "end"),
    ("🔛", "on"),
    ("🔜", "soon"),
    ("🔝", "top up"),
    ("⏫", "fast up double"),
    ("⏬", "fast down double"),
    ("⏭️", "next track skip"),
    ("⏮️", "previous track back"),
    ("▶️", "play button"),
    ("⏩", "fast forward"),
    ("⏯️", "play pause"),
    ("⏪", "rewind"),
    ("⏸️", "pause button"),
    ("⏹️", "stop button"),
    ("⏺️", "record button"),
    ("⏏️", "eject button"),
    ("🎦", "cinema film movie"),
    ("🔅", "dim brightness low"),
    ("🔆", "bright brightness high"),
    ("📶", "signal bars wifi"),
    ("📳", "vibration phone"),
    ("📴", "phone off silent"),
    ("♀️", "female sign woman"),
    ("♂️", "male sign man"),
    ("⚧️", "transgender symbol"),
    ("✖️", "multiply x close"),
    ("➕", "plus add"),
    ("➖", "minus subtract"),
    ("➗", "divide"),
    ("🟰", "equals"),
    ("♾️", "infinity forever"),
    ("‼️", "double exclamation"),
    ("⁉️", "exclamation question"),
    ("❓", "question mark help red"),
    ("❔", "white question help"),
    ("❕", "white exclamation"),
    ("❗", "exclamation mark warning red"),
    ("〰️", "wavy dash"),
    ("💱", "currency exchange money"),
    ("💲", "dollar sign money heavy"),
    ("⚕️", "medical symbol staff"),
    ("♻️", "recycle reuse green"),
    ("⚜️", "fleur de lis"),
    ("🔱", "trident emblem"),
    ("📛", "name badge"),
    ("🔰", "beginner japanese"),
    ("⭕", "hollow red circle correct"),
    ("✅", "check"),
    ("🛑", "stop sign octagon"),
    ("🚫", "prohibited no forbidden"),
    ("💯", "hundred"),
    ("🔞", "underage no 18"),
    ("📵", "no phones banned"),
    ("🚯", "no littering"),
    ("🚱", "no drinking water"),
    ("🚷", "no pedestrians"),
    ("📛", "name badge"),
    ("🔞", "no one under eighteen"),
    ("☢️", "radioactive nuclear"),
    ("☣️", "biohazard danger"),
    ("⬆️", "up"),
    ("↗️", "up right"),
    ("➡️", "right"),
    ("↘️", "down right"),
    ("⬇️", "down"),
    ("↙️", "down left"),
    ("⬅️", "left"),
    ("↖️", "up left"),
    // activities
    ("⚽", "soccer ball football sport"),
    ("🏀", "basketball sport"),
    ("🏈", "american football sport"),
    ("⚾", "baseball sport"),
    ("🥎", "softball sport"),
    ("🎾", "tennis sport"),
    ("🏐", "volleyball sport"),
    ("🏉", "rugby football sport"),
    ("🥏", "flying disc frisbee"),
    ("🎱", "pool 8ball billiards"),
    ("🪀", "yo-yo toy"),
    ("🏓", "ping pong table tennis"),
    ("🏸", "badminton"),
    ("🏒", "hockey ice"),
    ("🏑", "field hockey"),
    ("🥍", "lacrosse"),
    ("🏏", "cricket bat ball"),
    ("🪃", "boomerang"),
    ("🥅", "goal net soccer"),
    ("⛳", "golf flag hole"),
    ("🪁", "kite fly"),
    ("🏹", "bow arrow archery"),
    ("🎣", "fishing rod"),
    ("🤿", "diving mask snorkel"),
    ("🥊", "boxing glove fight"),
    ("🥋", "martial arts uniform karate judo"),
    ("🎽", "running shirt singlet"),
    ("🛹", "skateboard"),
    ("🛼", "roller skate"),
    ("🛷", "sled snow"),
    ("⛸️", "ice skate"),
    ("🥌", "curling stone"),
    ("🎿", "skis snow"),
    ("⛷️", "skier snow"),
    ("🏂", "snowboarder snow"),
    ("🪂", "parachute skydive"),
    ("🏋️", "weightlifter gym lift"),
    ("🤼", "wrestlers fight"),
    ("🤸", "cartwheel gymnastics"),
    ("⛹️", "basketball player bounce"),
    ("🤺", "fencer fencing sword"),
    ("🤾", "handball throw"),
    ("🏌️", "golfer golf swing"),
    ("🏇", "horse racing jockey"),
    ("🧘", "yoga meditate lotus"),
    ("🏄", "surfer surf wave"),
    ("🏊", "swimmer swim pool"),
    ("🤽", "water polo"),
    ("🚣", "rowboat row kayak"),
    ("🧗", "climbing rock"),
    ("🚵", "mountain biker bike"),
    ("🚴", "bicyclist bike cycling"),
    ("🏆", "trophy win champion"),
    ("🥇", "gold medal first winner"),
    ("🥈", "silver medal second"),
    ("🥉", "bronze medal third"),
    ("🏅", "sports medal award"),
    ("🎖️", "military medal honor"),
    ("🏵️", "rosette award"),
    ("🎗️", "ribbon reminder awareness"),
    ("🎫", "ticket event"),
    ("🎟️", "tickets admission event"),
    ("🎪", "circus tent"),
    ("🤹", "juggler circus"),
    ("🎭", "theater masks drama performing"),
    ("🩰", "ballet dancer pointe"),
    ("🎨", "art palette paint"),
    ("🎬", "clapper board film movie"),
    ("🎤", "microphone sing karaoke"),
    ("🎧", "headphones music listen"),
    ("🎼", "musical score notes"),
    ("🎹", "piano keyboard music"),
    ("🥁", "drum music"),
    ("🪘", "long drum"),
    ("🎷", "saxophone jazz music"),
    ("🎺", "trumpet music"),
    ("🪗", "accordion music"),
    ("🎸", "guitar rock music"),
    ("🪕", "banjo music"),
    ("🎻", "violin music"),
    ("🪉", "harp music"),
    ("🎲", "dice game random"),
    ("♟️", "pawn chess"),
    ("🎯", "target dart bullseye direct hit"),
    ("🎳", "bowling ball"),
    ("🎮", "video game controller gaming"),
    ("🎰", "slot machine casino"),
    ("🧩", "puzzle piece jigsaw"),
    // travel and places
    ("🚗", "car automobile drive"),
    ("🚕", "taxi cab"),
    ("🚙", "suv car"),
    ("🚌", "bus"),
    ("🚎", "trolleybus"),
    ("🏎️", "racing car f1 fast"),
    ("🚓", "police car"),
    ("🚑", "ambulance emergency"),
    ("🚒", "fire engine truck"),
    ("🚐", "minibus van"),
    ("🛻", "pickup truck"),
    ("🚚", "truck delivery"),
    ("🚛", "semi truck lorry"),
    ("🚜", "tractor farm"),
    ("🦯", "white cane blind"),
    ("🦽", "manual wheelchair"),
    ("🦼", "motorized wheelchair"),
    ("🛴", "scooter kick"),
    ("🚲", "bicycle bike cycling"),
    ("🛵", "motor scooter vespa"),
    ("🏍️", "motorcycle motorbike"),
    ("🛺", "auto rickshaw tuktuk"),
    ("🚨", "police siren emergency light"),
    ("🚔", "police car oncoming"),
    ("🚍", "bus oncoming"),
    ("🚘", "car oncoming"),
    ("🚖", "taxi oncoming"),
    ("🚡", "cable car aerial"),
    ("🚠", "mountain cableway gondola"),
    ("🚟", "suspension railway"),
    ("🚃", "railway car tram"),
    ("🚋", "tram trolley"),
    ("🚞", "mountain railway"),
    ("🚝", "monorail"),
    ("🚄", "bullet train shinkansen fast"),
    ("🚅", "bullet train fast"),
    ("🚈", "light rail"),
    ("🚂", "locomotive train steam"),
    ("🚆", "train"),
    ("🚇", "metro subway underground"),
    ("🚊", "tram"),
    ("🚉", "station train"),
    ("✈️", "airplane flight travel plane"),
    ("🛫", "departure plane takeoff"),
    ("🛬", "arrival plane landing"),
    ("🪂", "parachute"),
    ("💺", "seat airplane chair"),
    ("🚁", "helicopter"),
    ("🛸", "flying saucer ufo"),
    ("🚀", "rocket launch space ship fast"),
    ("🛰️", "satellite space"),
    ("⛵", "sailboat sailing"),
    ("🛶", "canoe kayak boat"),
    ("🚤", "speedboat fast"),
    ("🛥️", "motorboat yacht"),
    ("🛳️", "cruise ship passenger"),
    ("⛴️", "ferry boat"),
    ("🚢", "ship boat"),
    ("⚓", "anchor ship navy"),
    ("🪝", "hook"),
    ("⛽", "fuel pump gas petrol"),
    ("🚧", "construction barrier work"),
    ("🚦", "traffic light vertical"),
    ("🚥", "traffic light horizontal"),
    ("🚏", "bus stop"),
    ("🗺️", "world map travel"),
    ("🗿", "moai statue easter island"),
    ("🗽", "statue of liberty new york"),
    ("🗼", "tokyo tower"),
    ("🏰", "castle europe"),
    ("🏯", "japanese castle"),
    ("🏟️", "stadium arena"),
    ("🎡", "ferris wheel carnival"),
    ("🎢", "roller coaster amusement"),
    ("🎠", "carousel horse merry"),
    ("⛲", "fountain"),
    ("⛱️", "umbrella beach sun"),
    ("🏖️", "beach umbrella sand vacation"),
    ("🏝️", "island desert vacation"),
    ("🏜️", "desert cactus"),
    ("🌋", "volcano lava eruption"),
    ("⛰️", "mountain"),
    ("🏔️", "snow mountain"),
    ("🗻", "mount fuji japan"),
    ("🏕️", "camping tent"),
    ("⛺", "tent camping"),
    ("🏠", "house home"),
    ("🏡", "house garden home"),
    ("🏢", "office building work"),
    ("🏣", "japanese post office"),
    ("🏤", "post office european"),
    ("🏥", "hospital doctor"),
    ("🏦", "bank money"),
    ("🏨", "hotel"),
    ("🏩", "love hotel"),
    ("🏪", "convenience store shop"),
    ("🏫", "school building"),
    ("🏬", "department store mall"),
    ("🏭", "factory industry"),
    ("🏯", "castle"),
    ("🏰", "castle"),
    ("💒", "wedding chapel church"),
    ("🗼", "tower"),
    ("🗽", "liberty"),
    ("⛪", "church wedding"),
    ("🕌", "mosque islam"),
    ("🛕", "hindu temple"),
    ("🕍", "synagogue jewish"),
    ("⛩️", "shinto shrine japan"),
    ("🕋", "kaaba mecca islam"),
    ("⛲", "fountain"),
    ("🌃", "night city stars"),
    ("🏙️", "cityscape skyline"),
    ("🌄", "sunrise mountains"),
    ("🌅", "sunrise"),
    ("🌆", "city dusk sunset"),
    ("🌇", "city sunset"),
    ("🌉", "bridge night"),
    ("♨️", "hot springs onsen steam"),
    ("🎠", "carousel"),
    ("🛝", "slide playground"),
    ("🎪", "circus"),
    // nature
    ("🌵", "cactus desert"),
    ("🎄", "christmas tree holiday"),
    ("🌲", "evergreen tree pine"),
    ("🌳", "tree deciduous"),
    ("🌴", "palm tree beach tropical"),
    ("🪴", "potted plant"),
    ("🌱", "seedling sprout grow plant"),
    ("🌿", "herbs leaf green"),
    ("☘️", "shamrock clover lucky irish"),
    ("🍀", "four leaf clover lucky"),
    ("🎍", "pine decoration japanese new year"),
    ("🎋", "tanabata tree wish"),
    ("🍃", "leaves wind flutter"),
    ("🍂", "fallen leaves autumn"),
    ("🍁", "maple leaf canada autumn"),
    ("🪹", "empty nest bird"),
    ("🪺", "nest eggs bird"),
    ("🍄", "mushroom toadstool"),
    ("🐚", "shell seashell beach"),
    ("🪨", "rock stone"),
    ("🌾", "sheaf rice grain wheat"),
    ("💐", "bouquet flowers"),
    ("🌷", "tulip flower"),
    ("🌹", "rose flower love red"),
    ("🪷", "lotus flower"),
    ("🪻", "hyacinth flower"),
    ("🌺", "hibiscus flower"),
    ("🌻", "sunflower"),
    ("🌼", "blossom flower daisy"),
    ("🌸", "cherry blossom sakura pink"),
    ("💮", "white flower japanese"),
    ("🏵️", "rosette flower"),
    ("🌺", "hibiscus"),
    // office and study
    ("💼", "briefcase work bag office"),
    ("📁", "folder file directory"),
    ("📂", "open folder files"),
    ("🗂️", "card index dividers"),
    ("📅", "calendar date"),
    ("📆", "tear off calendar"),
    ("🗒️", "spiral notepad note"),
    ("🗓️", "spiral calendar"),
    ("📇", "card index rolodex"),
    ("📈", "chart up growth trend"),
    ("📉", "chart down decline trend"),
    ("📊", "bar chart stats data"),
    ("📋", "clipboard copy paste"),
    ("📌", "pushpin pin"),
    ("📍", "pin location map"),
    ("📎", "paperclip attach"),
    ("🖇️", "linked paperclips"),
    ("📏", "ruler measure straight"),
    ("📐", "triangular ruler measure"),
    ("✂️", "scissors cut"),
    ("🗃️", "card file box"),
    ("🗄️", "file cabinet"),
    ("📰", "newspaper news"),
    ("🗞️", "rolled newspaper"),
    ("📓", "notebook"),
    ("📔", "notebook cover"),
    ("📒", "ledger notebook"),
    ("📕", "closed book red"),
    ("📗", "green book"),
    ("📘", "blue book"),
    ("📙", "orange book"),
    ("📚", "books library read study"),
    ("📖", "open book read"),
    ("🔖", "bookmark save"),
    ("🧷", "safety pin"),
    ("🔗", "link chain url connect"),
    ("📎", "paperclip"),
    ("📯", "postal horn"),
    ("📫", "mailbox flag up mail"),
    ("📪", "mailbox closed mail"),
    ("📬", "mailbox open mail"),
    ("📭", "mailbox empty"),
    ("📮", "postbox mail send"),
    ("🗳️", "ballot box vote election"),
    ("✏️", "pencil write edit"),
    ("✒️", "pen nib fountain write"),
    ("🖋️", "fountain pen write"),
    ("🖊️", "pen write ballpoint"),
    ("🖌️", "paintbrush paint art"),
    ("🖍️", "crayon draw color"),
    ("📝", "memo note write pad"),
    ("💼", "briefcase"),
    ("📁", "folder"),
    ("📂", "open folder"),
    ("📅", "calendar"),
    ("📊", "chart"),
    ("💰", "money"),
    ("🔍", "magnifying glass search find zoom"),
    ("🔎", "magnifying glass tilted search find"),
    ("🔏", "locked pen private secure"),
    ("🔐", "locked key secure"),
    ("🔒", "locked lock secure private"),
    ("🔓", "unlocked open lock"),
    ("🔑", "key password access"),
    ("🗝️", "old key"),
    ("🔨", "hammer"),
    ("🪓", "axe"),
    ("⛏️", "pick"),
    ("⚒️", "hammer and pick"),
    ("🛠️", "hammer wrench"),
    ("🗡️", "dagger knife"),
    ("⚔️", "crossed swords fight battle"),
    ("💣", "bomb"),
    ("🪃", "boomerang"),
    ("🏹", "bow arrow"),
    ("🛡️", "shield"),
    ("🪚", "carpentry saw"),
    ("🔧", "wrench"),
    ("🪛", "screwdriver"),
    ("🔩", "nut bolt"),
    ("⚙️", "gear"),
    ("🗜️", "clamp"),
    ("⚖️", "balance scale"),
    ("🦯", "cane"),
    ("🔗", "link"),
    ("⛓️‍💥", "broken chain"),
    ("🧰", "toolbox"),
    ("🧲", "magnet"),
    ("🪜", "ladder"),
    ("⚗️", "alembic chemistry science"),
    ("🧪", "test tube science lab experiment"),
    ("🧫", "petri dish biology"),
    ("🧬", "dna genetics science"),
    ("🔬", "microscope science lab"),
    ("🔭", "telescope astronomy space"),
    ("📡", "satellite"),
    ("💉", "syringe vaccine shot"),
    ("🩸", "blood drop"),
    ("💊", "pill medicine drug"),
    ("🩹", "bandage adhesive plaster"),
    ("🩼", "crutch"),
    ("🩺", "stethoscope doctor"),
    ("🩻", "x-ray bones"),
    ("🚑", "ambulance"),
    ("🦠", "microbe virus bacteria germ"),
    // music and media
    ("🎵", "musical note music"),
    ("🎶", "musical notes music song"),
    ("🎼", "musical score"),
    ("🎧", "headphones"),
    ("📻", "radio"),
    ("🎷", "saxophone"),
    ("🪗", "accordion"),
    ("🎸", "guitar"),
    ("🎹", "piano"),
    ("🎺", "trumpet"),
    ("🎻", "violin"),
    ("🪕", "banjo"),
    ("🥁", "drum"),
    ("🪘", "long drum"),
    ("🪇", "maracas"),
    ("🪈", "flute"),
    ("🎤", "microphone"),
];

#[derive(Default)]
pub struct EmojiPickerCommand;

corvo_core::register_command!(EmojiPickerCommand);

#[async_trait::async_trait]
impl Command for EmojiPickerCommand {
    fn id(&self) -> &'static str {
        "emoji-picker"
    }

    fn keywords(&self) -> &'static [&'static str] {
        &["emoji", "emoticon", "smiley"]
    }

    async fn search(&self, query: &str, ctx: &SearchContext) -> Vec<SearchResult> {
        let q = query.trim().to_lowercase();
        if let Some(subquery) = q.strip_prefix("emoji-page:") {
            let sub = subquery.trim();
            if sub.is_empty() {
                return all_emojis();
            }
            return search_emojis(sub, ctx.max_results);
        }

        if q.is_empty() {
            return vec![SearchResult {
                id: "emoji-picker:open".into(),
                title: "Search Emoji & Symbols".into(),
                subtitle: Some("Commands".into()),
                icon: Icon::Svg(phosphor_svgs::style::regular::SMILEY),
                score: 1000,
                accessory: Some("cmd+alt+space".into()),
            }];
        }

        let mut results = Vec::new();
        if let Some(score) = search_match_score(
            &q,
            &["Search Emoji & Symbols", "emoji emoticon smiley symbols"],
        ) {
            results.push(SearchResult {
                id: "emoji-picker:open".into(),
                title: "Search Emoji & Symbols".into(),
                subtitle: Some("Commands".into()),
                icon: Icon::Svg(phosphor_svgs::style::regular::SMILEY),
                score: score + 120,
                accessory: Some("cmd+alt+space".into()),
            });
        }
        results
    }

    async fn execute(&self, result_id: &str, _ctx: &ExecutionContext) -> Result<Action, CommandError> {
        if result_id == "emoji-picker:open" {
            return Ok(Action::ShowToast("Search Emoji & Symbols".into()));
        }
        let Some(glyph) = result_id.strip_prefix("emoji-picker:") else {
            return Err(CommandError::NotFound);
        };
        if EMOJI.iter().any(|(known, _)| *known == glyph) {
            Ok(Action::PasteText(glyph.to_owned()))
        } else {
            Err(CommandError::NotFound)
        }
    }

    fn actions(&self, result_id: &str) -> Vec<CommandAction> {
        if result_id == "emoji-picker:open" {
            return vec![
                CommandAction {
                    id: "emoji-picker-action:open".into(),
                    label: "Open Emoji & Symbols".into(),
                    action: Action::ShowToast("Search Emoji & Symbols".into()),
                    icon: Icon::Svg(phosphor_svgs::style::regular::SMILEY),
                    group: ActionGroup::Primary,
                    hotkey: Some("enter"),
                },
            ];
        }
        let Some(glyph) = result_id.strip_prefix("emoji-picker:") else {
            return Vec::new();
        };
        if !EMOJI.iter().any(|(known, _)| *known == glyph) {
            return Vec::new();
        }
        vec![
            CommandAction {
                id: "emoji-picker-action:paste".into(),
                label: "Paste to Active App".into(),
                action: Action::PasteText(glyph.to_owned()),
                icon: Icon::Svg(phosphor_svgs::style::regular::ARROW_BEND_DOWN_LEFT),
                group: ActionGroup::Primary,
                hotkey: Some("enter"),
            },
            CommandAction {
                id: "emoji-picker-action:copy".into(),
                label: "Copy Emoji".into(),
                action: Action::Copy(glyph.to_owned()),
                icon: Icon::Svg(phosphor_svgs::style::regular::COPY),
                group: ActionGroup::Standard,
                hotkey: Some("cmd+enter"),
            },
        ]
    }
}

/// Category name for an emoji by its position in the static corpus.
pub fn category_for_index(index: usize) -> &'static str {
    match index {
        0..=91 => "Smileys & Emotion",
        92..=144 => "People & Body",
        145..=219 => "Hearts & Symbols",
        220..=285 => "Animals & Nature",
        286..=398 => "Food & Drink",
        399..=531 => "Objects",
        532..=620 => "Symbols",
        621..=705 => "Arrows & UI",
        706..=793 => "Activities",
        794..=915 => "Travel & Places",
        916..=948 => "Nature",
        949..=1053 => "Office & Study",
        _ => "Music & Media",
    }
}

/// The first keywords read as the display name.
fn display_name(keywords: &str) -> String {
    keywords.split_whitespace().take(2).collect::<Vec<_>>().join(" ")
}

static ALL_EMOJIS: std::sync::OnceLock<Vec<SearchResult>> = std::sync::OnceLock::new();
static EMOJI_TEXTS: std::sync::OnceLock<Vec<corvo_core::search::SearchText>> = std::sync::OnceLock::new();

pub fn warmup() {
    let _ = all_emojis();
}

/// All emojis in the static corpus.
pub fn all_emojis() -> Vec<SearchResult> {
    ALL_EMOJIS
        .get_or_init(|| {
            EMOJI
                .iter()
                .enumerate()
                .map(|(idx, &(glyph, keywords))| {
                    let category = category_for_index(idx);
                    SearchResult {
                        id: format!("emoji-picker:{glyph}"),
                        title: display_name(keywords),
                        subtitle: Some(category.to_string()),
                        icon: Icon::Glyph(glyph),
                        score: 500,
                        accessory: Some(category.into()),
                    }
                })
                .collect()
        })
        .clone()
}

/// Fuzzy search across all emojis in the corpus using precomputed SearchText and quality/DP alignment.
pub fn search_emojis(query: &str, max_results: usize) -> Vec<SearchResult> {
    let q = query.trim();
    if q.is_empty() {
        return all_emojis().into_iter().take(max_results).collect();
    }

    let q_text = corvo_core::search::SearchText::new(q);
    let texts = EMOJI_TEXTS.get_or_init(|| {
        EMOJI
            .iter()
            .map(|(_, keywords)| corvo_core::search::SearchText::new(keywords))
            .collect()
    });

    let mut scored: Vec<(usize, i32)> = Vec::new();
    for (idx, kw_text) in texts.iter().enumerate() {
        let fields = [(corvo_core::search::FieldRole::Name, kw_text)];
        if let Some(quality) = corvo_core::search::quality(&q_text, &fields) {
            scored.push((idx, quality));
        } else if let Some(dp) = corvo_core::search::match_launcher_dp(
            &q_text,
            kw_text,
            corvo_core::search::SearchSensitivity::Medium,
        ) {
            scored.push((idx, 500 + dp));
        }
    }

    scored.sort_by(|a, b| b.1.cmp(&a.1));

    scored
        .into_iter()
        .take(max_results)
        .map(|(idx, score)| {
            let &(glyph, keywords) = &EMOJI[idx];
            let category = category_for_index(idx);
            SearchResult {
                id: format!("emoji-picker:{glyph}"),
                title: display_name(keywords),
                subtitle: Some(category.to_string()),
                icon: Icon::Glyph(glyph),
                score,
                accessory: Some(category.into()),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{EMOJI, EmojiPickerCommand};
    use corvo_core::{Action, Command, ExecutionContext, SearchContext};

    fn search(query: &str) -> Vec<corvo_core::SearchResult> {
        let command = EmojiPickerCommand;
        let ctx = SearchContext { max_results: 10, store: None };
        smol::block_on(command.search(&format!("emoji-page:{query}"), &ctx))
    }

    #[test]
    fn search_matches_a_name() {
        let results = search("rocket");
        assert!(!results.is_empty());
        assert!(results.iter().any(|result| result.id == "emoji-picker:🚀"));
    }

    #[test]
    fn search_with_no_match_is_empty() {
        assert!(search("zzzzqqq").is_empty());
    }

    #[test]
    fn execute_copies_the_glyph_verbatim() {
        let command = EmojiPickerCommand;
        let ctx = ExecutionContext::default();
        let action = smol::block_on(command.execute("emoji-picker:🚀", &ctx));
        assert_eq!(action, Ok(Action::PasteText("🚀".into())));
        assert!("🚀".as_bytes() == [0xF0, 0x9F, 0x9A, 0x80]);
    }

    #[test]
    fn finds_emoji_by_keyword() {
        let entry = EMOJI.iter().find(|(_, keywords)| keywords.contains("rocket"));
        assert!(entry.is_some());
        assert_eq!(entry.map(|(glyph, _)| *glyph), Some("🚀"));
    }

    #[test]
    fn search_attaches_category() {
        let results = search("rocket");
        assert!(!results.is_empty());
        let rocket = results.iter().find(|r| r.id == "emoji-picker:🚀").unwrap();
        assert_eq!(rocket.subtitle.as_deref(), Some("Travel & Places"));
    }

    #[test]
    fn rejects_unknown_queries() {
        let entry = EMOJI.iter().find(|(_, keywords)| keywords.contains("zzzzqqq"));
        assert!(entry.is_none());
    }

    #[test]
    fn root_search_empty_returns_command() {
        let command = EmojiPickerCommand;
        let ctx = SearchContext { max_results: 10, store: None };
        let results = smol::block_on(command.search("", &ctx));
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].id, "emoji-picker:open");
    }

    #[test]
    fn root_search_emoji_keyword_returns_command() {
        let command = EmojiPickerCommand;
        let ctx = SearchContext { max_results: 10, store: None };
        let results = smol::block_on(command.search("emoji", &ctx));
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].id, "emoji-picker:open");
    }
}
