[package]
name = "corvo-clipboard-manager"
version = "0.5.1"
edition = "2021"
publish = false

[dependencies]
async-trait = { workspace = true }
corvo-core = { workspace = true }
corvo-platform = { workspace = true }
directories = { workspace = true }
serde = { workspace = true }
serde_json = "1"
smol = { workspace = true }
chrono = { workspace = true }
