[package]
name = "corvo-app-launcher"
version = "0.3.3"
edition = "2021"
publish = false

[dependencies]
async-trait = { workspace = true }
corvo-config = { workspace = true }
corvo-core = { workspace = true }
corvo-platform = { workspace = true }
smol = { workspace = true }
serde = { workspace = true }
serde_json = "1"
