//! Resident launcher binary. Wires the command registry, single-instance
//! IPC, the global hotkey, and the GPUI window. Adding a command never
//! touches this file; see AGENT.md.

#![cfg_attr(target_os = "windows", windows_subsystem = "windows")]

use corvo_core::CommandRegistry;
use corvo_platform::ipc;

// Linker anchors for every command crate; generated by build.rs. Adding
// a command never touches this file; see AGENT.md.
include!(concat!(env!("OUT_DIR"), "/linked_commands.rs"));

fn main() {
    // A second invocation only toggles the resident instance (SPEC §6).
    // `--toggle` takes the same path: when no resident answers, this
    // process becomes the resident, so a compositor-bound hotkey still
    // works after a crash or a quit.
    match ipc::try_send_toggle() {
        ipc::StartupDecision::StartResident => {}
        ipc::StartupDecision::ToggleExisting => return,
        ipc::StartupDecision::ExistingWithoutToggle => {
            eprintln!("corvo: another resident is active but did not accept the toggle request");
            return;
        }
    }

    let (ipc_tx, ipc_rx) = smol::channel::unbounded::<()>();
    ipc::serve(ipc_tx);

    corvo_platform::cleanup_old_installations();
    corvo_app_launcher::warmup();
    corvo_emoji_picker::warmup();
    let config = corvo_config::ConfigService::load();
    if config.settings().launch_at_login {
        let _ = corvo_platform::set_launch_at_login(true);
    }
    let clipboard = &config.settings().clipboard;
    corvo_clipboard_manager::set_preferences(corvo_clipboard_manager::ClipboardPreferences {
        enabled: clipboard.enabled,
        retention_days: clipboard.retention_days,
        max_entries: clipboard.max_entries,
        save_images: clipboard.save_images,
        save_colors: clipboard.save_colors,
    });
    corvo_clipboard_manager::start_watcher();
    let store = config.shared();
    let (intent_tx, intent_rx) = smol::channel::unbounded::<corvo_platform::HotkeyIntent>();

    // Forward IPC toggles to the intent channel
    let ipc_forward_tx = intent_tx.clone();
    smol::spawn(async move {
        while ipc_rx.recv().await.is_ok() {
            let _ = ipc_forward_tx.try_send(corvo_platform::HotkeyIntent::ToggleLauncher);
        }
    })
    .detach();

    let registry = CommandRegistry::from_inventory();
    eprintln!("corvo: {} commands registered", registry.commands().len());
    corvo_ui::preload_initial_results(&registry, store.clone());
    corvo_ui::run(registry, store, intent_tx, intent_rx);
}
