//! Resident launcher binary. Wires the command registry, single-instance
//! IPC, the global hotkey, and the GPUI window. Adding a command never
//! touches this file; see AGENT.md.

use corvo_core::CommandRegistry;
use corvo_platform::{hotkey, ipc};

// Linker anchors for every command crate; generated by build.rs. Adding
// a command never touches this file; see AGENT.md.
include!(concat!(env!("OUT_DIR"), "/linked_commands.rs"));

fn main() {
    // A second invocation only toggles the resident instance (SPEC §6).
    // `--toggle` takes the same path: when no resident answers, this
    // process becomes the resident, so a compositor-bound hotkey still
    // works after a crash or a quit.
    if ipc::try_send_toggle() {
        return;
    }

    corvo_app_launcher::warmup();
    corvo_emoji_picker::warmup();
    corvo_clipboard_manager::start_watcher();

    let _config = corvo_config::ConfigService::load();
    let (tx, rx) = smol::channel::unbounded::<()>();
    ipc::serve(tx.clone());
    let _hotkey = hotkey::setup(tx);

    let registry = CommandRegistry::from_inventory();
    eprintln!("corvo: {} commands registered", registry.commands().len());
    corvo_ui::preload_initial_results(&registry);
    corvo_ui::run(registry, rx);
}
